services:
  server:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  client:
    image: postgres:17
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: server
    depends_on:
      - server
    volumes:
      - ".:/sql"
    command: |
      /bin/bash -eux -c "
        sleep 10s
        psql --file=/sql/temp-table-do-instead.sql
      "
