# https://www.postgresql.org/docs/current/ssl-tcp.html
version: "3.7"
services:
  ssl:
    image: alpine:latest
    command: ./generate-ssl-certs.sh
    volumes:
    - ssl-certs:/data/ssl/certs
    - ./generate-ssl-certs.sh:/generate-ssl-certs.sh:ro

  server:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
    - ssl
    volumes:
    - ssl-certs:/data/ssl/certs:ro
    - ./configure-server-ssh.sh:/docker-entrypoint-initdb.d/configure-server-ssh.sh:ro

  client:
    image: postgres:14-alpine
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: server
      PGSSLMODE: require
    depends_on:
    - server
    command: |
      /bin/bash -eux -c "
        pg_isready --timeout=300
        psql --command='
          show ssl;
        '
      "

volumes:
  ssl-certs:
