version: "3.7"
services:

  client:
    image: postgres:15-alpine
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
      PGDATABASE: db
      PGSSLMODE: require
    command: |
      /bin/bash -eux -c "
        psql --echo-all --file=/schema-and-data.sql
        PGUSER=user1 PGPASSWORD=p0sTgres psql --echo-all --file=/user1.sql
        PGUSER=user2 PGPASSWORD=p0sTgres psql --echo-all --file=/user2.sql
        psql --echo-all --file=/table-metadata.sql
      "
    volumes:
      - ./schema-and-data.sql:/schema-and-data.sql:ro
      - ./user1.sql:/user1.sql:ro
      - ./user2.sql:/user2.sql:ro
      - ./table-metadata.sql:/table-metadata.sql:ro
